version: "3.3"
services:
  switchboard:
    image: "switchboardlabs/node:staging"
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - LIVE=1
      - CLUSTER=devnet
      - FULFILLMENT_MANAGER_KEY=GraetK8qufsXv5bUGmeXMGojGLbDwZ3XApsnt9fdk9Bu
      - FULFILLMENT_MANAGER_HEARTBEAT_AUTH_KEY=44FV1sr38XAojRhmcgBAcJohWvK4T5wJqDBSkWGEEMPM
secrets:
  PAYER_SECRETS:
    file: ./main-account.json