version: "3.3"
services:
  switchboard:
    image: "switchboardlabs/node:staging"
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - LIVE=1
      - CLUSTER=devnet
      - FULFILLMENT_MANAGER_KEY=54iM3ZCkobRczm77apBKTskmCh5LdJV3BMR7Z7FAKR5w
      - FULFILLMENT_MANAGER_HEARTBEAT_AUTH_KEY=82JbAj4aGeEtdNwr5o1FHsRA2QY8uDvsfdgRuvPURz9D
secrets:
  PAYER_SECRETS:
    file: ./main-account.json